title: Mijn script heeft geen fouten, maar de methods ervan worden niet uitgevoerd
hero_image: images/banner.png
description: Mijn script heeft geen fouten, maar de methods ervan worden niet uitgevoerd
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - 
    title: Mijn script heeft geen fouten, maar de methods ervan worden niet uitgevoerd
