title: My script has no errors but its methods are not running
hero_image: images/banner.png
description: My script has no errors but its methods are not running
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: My script has no errors but its methods are not running
